#' Summarize Simulated Literature Data
#'
#' This function summarizes the simulated literature returned by [simulate_literature()].
#'
#' @param literature (`list`)\cr
#'   The simulated literature data, generated by [simulate_literature()].
#' @param simple (`logical()`)\cr
#'   If `TRUE`, the output will be simplified to only contain a selection of key columns.
#'   If `FALSE` the output will also contain all columns of `complete_studies` passed to / created by [simulate_literature][`simulate_literature()`].
#'   Default is `TRUE`.
#'
#' @return (`data.frame`)\cr
#' A `data.frame` giving an overview over the simulated literature, with the following columns if `simple = FALSE`:
#' * `study_id` (`integer()` or `character()`)\cr
#'   The unique identifier of the study
#' * `agent_id` (`integer()` or `character()`)\cr
#'   The unique identifier of the agent who performed the data analysis.
#' * `N` (`integer()`)\cr
#'   Number of code units in the study.
#' * `resources` (`numeric()`)\cr
#'   Total resources available for the study.
#' * `cost` (`numeric()`)\cr
#'   Cost associated with one search round for the study.
#' * `benefit` (`numeric()`)\cr
#'   Benefit associated with one search round for the study.
#' * `bcr` (`numeric()`)\cr
#'   Benefit-cost ratio for the study.
#' * `n_rounds` (`integer()`)\cr
#'   Number of rounds the agent searched for faults.
#'   If `N+1`, this means that the agent finished the last round instead of stopping in the last round.
#' * `reason` (`character()`)\cr
#'   Reason for stopping the search. Can be "Search completed", "Expected utility too low" or "Resources depleted".
#' * `n_faults_total` (`integer()`)\cr
#'   Total number of faults in the study.
#' * `n_faults_discovered` (`integer()`)\cr
#'   Number of faults discovered by the agent.
#' * `n_faults_undiscovered` (`integer()`)\cr
#'   Number of faults not discovered by the agent.
#' * `real_effect_sizes` (`numeric()`)\cr
#'   Real effect size of the study (i.e. in the objective reality).
#' * `final_observed_effect_sizes` (`numeric()`)\cr
#'   Final observed effect size of the study in the round the agent stopped searching.
#' If `simple = TRUE` the returned `data.frame` contains all columns listed above as well as all input parameters.
#'
#' @examples
#' \dontrun{
#' # Create study and agent
#' agent <- create_agents(
#'
#' )
#' study <- create_studies(
#'
#' )
#'
#' # Simulate the study
#' lit <- simulate_literature(agents = agent, studies = study, seed = 123)
#'
#' # Summarize the literature (simple = TRUE)
#' simulation_summary(lit)
#'
#' # Extensive Summary with all input parameters
#' ext_summary <- simulation_summary(lit, simple = FALSE)
#'
#' # You can then index the information you need
#'
#' @export
simulation_summary <- function(literature, simple = TRUE) {
  assert_literature(literature)

  df = data.frame(
    study_id = names(literature),
    agent_id = sapply(literature, function(x) x$params$agent_id),
    stopped_in_round = sapply(literature, function(x) x$stop_conditions$stopped_in_round),
    stopping_reason = sapply(literature, function(x) x$stop_conditions$stopping_reason),
    final_resources = sapply(literature, function(x) x$stop_conditions$final_resources),
    n_faults_total = sapply(literature, function(x) x$objective_reality$true_K),
    n_faults_discovered = sapply(literature, function(x) x$stop_conditions$n_faults_discovered),
    true_effect = sapply(literature, function(x) x$objective_reality$true_effect),
    init_obs_effect = sapply(literature, function(x) {
      x$objective_reality$true_effect + sum(x$objective_reality$error_sizes)
    }),
    final_obs_effect = sapply(literature, function(x) x$stop_conditions$final_effect_size)
  )

  if (!simple) {
    params_df <- do.call(rbind, Map(function(id, x) c(study_id = id, x$params), names(literature), literature))
    df <- merge(df, params_df, by = c("study_id", "agent_id"))
    names(df)[names(df) == "resources"] <- "init_resources"  # to avoid confusion with final_resources
  }

  df
}
